allowBuilds:
  '@sentry/cli': true
  esbuild: true
  lefthook: true
  puppeteer: true
  sharp: true
  workerd: true

overrides:
  sharp: "^0.35.3"
  wrangler: "^4.106.0"

peerDependencyRules:
  allowedVersions:
    '@vite-pwa/astro>astro': "^6.0.0"
    '@astrojs/cloudflare>astro': "^6.0.0"
