main = "@astrojs/cloudflare/entrypoints/server"
name = "jefrydco"
compatibility_date = "2026-01-11"
compatibility_flags = ["nodejs_compat", "fetch_iterable_type_support"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[routes]]
pattern = "jefrydco.id"
custom_domain = true

[placement]
mode = "smart"
